title: "TFI - Modelos y Simulación"
description: "Simulación de eventos discretos del pipeline de revisión de Pull Requests en GitHub. Eric Doyle, Ingeniería en Informática (UNNOBA)."
theme: jekyll-theme-minimal
show_downloads: false